import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppHeader from "./_components/AppHeader";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Status bar Color for mobile devices */}
      {/* Chrome, Firefox OS and Opera */}
      <meta name="theme-color" content="#212529" />
      {/* Windows */}
      <meta name="msapplication-navbutton-color" content="#212529" />
      {/* iOS Safari */}
      <meta name="apple-mobile-web-app-status-bar-style" content="#000" />
      <body className={inter.className}>
        <AppHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
